name: POC

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      a: ${{ steps.hash.outputs.a }}
      b: ${{ steps.hash.outputs.b }}

    strategy:
      matrix:
        modules:
          - name: a
          - name: b

    steps:
      - uses: actions/checkout@v4

      - id: hash
        working-directory:  ${{ matrix.modules.name }}
        run: |
          echo "${{matrix.modules.name}}=${{matrix.modules.name}}_${{hashFiles('1.txt', '2.txt', '3.txt', '4.txt')}}" >> $GITHUB_OUTPUT

  print:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "needs.setup.outputs.a=${{ needs.setup.outputs.a }}"
          echo "needs.setup.outputs.b=${{ needs.setup.outputs.b }}"
