name: POC

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      a: ${{ steps.hash.outputs.a }}
      b: ${{ steps.hash.outputs.b }}

    strategy:
      matrix:
        modules:
          - name: a
            files:
              - 'a/1.txt'
              - 'a/2.txt'
          - name: b
            files:
              - 'b/3.txt'
              - 'b/4.txt'

    steps:
      - uses: actions/checkout@v4

      - id: hash
        run: |
          echo "${{matrix.modules.name}}=hashFiles(${{join(matrix.modules.files, ', ')}})"
          echo "${{matrix.modules.name}}=${{matrix.modules.name}}_${{ hashFiles(join(matrix.modules.files, ', ')) }}" >> $GITHUB_OUTPUT

  print:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "needs.setup.outputs.a=${{ needs.setup.outputs.a }}"
          echo "needs.setup.outputs.b=${{ needs.setup.outputs.b }}"
